http://localhost:5000/accounts

###

http://localhost:5000/accounts/2

###

http://localhost:5000/accounts/-1

###

http://localhost:5000/accounts/20

###

http://localhost:5000/accounts/Peter

###

http://localhost:5000/accounts/Elliot

###

POST http://localhost:5000/accounts
content-type: application/json

{ 
    "name": null,
    "balance": 100
}

###

POST http://localhost:5000/accounts
content-type: application/json

{ 
    "name": "Test",
    "balance": -100
}

###

POST http://localhost:5000/accounts
content-type: application/json

{
    "name": "Elliot",
    "balance": 42
}

###

POST http://localhost:5000/accounts
content-type: application/json

{
    "name": "Grace",
    "balance": 1000
}

###


